version: 0.2
phases:
install:
  runtime-versions:
    python: 3.9
  commands:
    - pip install -r requirements.txt
build:
  commands:
    - streamlit run app.py --server.port=8501 --server.address=0.0.0.0 &
artifacts:
  files:
    - app.py
    - requirements.txt
    - .streamlit/**/*
    - amplify.yml